<a href="https://colab.research.google.com/github/zeeshan-ahmed-ai-tech/Artificial-Neural-Network/blob/main/lab(01)_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [ ]:
import torch
torch.__version__
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.zeros((3,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.eye(3)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.randint(0, 10, (3, 3))

tensor([[4, 5, 4],
        [1, 4, 0],
        [1, 6, 5]])

In [ ]:
import numpy as np
t= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
n= t.numpy()
print(n)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
arr = np.random.randint(0, 10, (3, 3))
print(arr)


[[8 4 0]
 [5 4 5]
 [2 3 4]]


In [ ]:
# Create a random NumPy array (3x3)
arr = np.random.randint(0, 10, (3, 3))
print("NumPy Array:")
print(arr)

# Convert NumPy array to PyTorch tensor
tensor_arr = torch.from_numpy(arr)
print("\nConverted to Tensor:")
print(tensor_arr)


NumPy Array:
[[7 4 1]
 [6 3 1]
 [8 8 6]]

Converted to Tensor:
tensor([[7, 4, 1],
        [6, 3, 1],
        [8, 8, 6]])


In [ ]:
n=np.random.rand(3,3).astype(np.float16)
t = torch.from_numpy(n)
print(t)

tensor([[0.5459, 0.1692, 0.1907],
        [0.1555, 0.5918, 0.6069],
        [0.0630, 0.8940, 0.2615]], dtype=torch.float16)


In [ ]:
# Create a 3x3 tensor filled with 1s
M = torch.ones(3, 3)

# Set diagonal elements to 2
M.fill_diagonal_(2)

print(M)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])


In [ ]:
t.device

device(type='cpu')

In [ ]:
# Step 1: Create a random matrix X ∈ R^(m×n)
m, n = 4, 5
X = torch.randn(m, n)
print("Matrix X:")
print(X)

# Step 2: Create a matrix Y ∈ R^(m×3) filled with ones (same number of rows as X)
Y = torch.ones(m, 3)
print("\nMatrix Y:")
print(Y)

Matrix X:
tensor([[-0.3851, -0.8488, -0.1821,  0.1433, -2.2875],
        [ 0.6899, -1.1710,  0.2456, -0.7612,  2.1977],
        [-0.4339,  1.1205,  0.0628,  0.6720,  1.3606],
        [-1.9385, -0.1280,  1.2025, -2.1365,  0.1533]])

Matrix Y:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
