<a href="https://colab.research.google.com/github/zeeshan-ahmed-ai-tech/Artificial-Neural-Network/blob/main/numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ===============================
# NumPy Array Creation and Operations
# ===============================

import numpy as np

# --- Creating Arrays ---
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)

print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

# --- Array Initialization ---
print("\nZeros array:\n", np.zeros((3, 4)))                   # Create an array of zeros
print("\nOnes array:\n", np.ones((2, 3, 4), dtype=np.int16))   # Create an array of ones
d = np.arange(10, 25, 5)                                       # Evenly spaced values (step = 5)
print("\nArray d (arange):\n", d)
print("\nLinspace array:\n", np.linspace(0, 2, 9))             # Evenly spaced samples
e = np.full((2, 2), 7)                                         # Constant array
print("\nFull array (7s):\n", e)
f = np.eye(2)                                                  # 2x2 Identity matrix
print("\nIdentity matrix f:\n", f)
print("\nRandom array:\n", np.random.random((2, 2)))           # Random values
print("\nEmpty array:\n", np.empty((3, 2)))                    # Empty array (uninitialized values)

# --- Arithmetic Operations ---
print("\nSubtraction (a - b):\n", a - b)
print("\nSubtraction using np.subtract:\n", np.subtract(a, b))
print("\nAddition (b + a):\n", b + a)
print("\nAddition using np.add:\n", np.add(b, a))
print("\nDivision (a / b):\n", a / b)
print("\nDivision using np.divide:\n", np.divide(a, b))
print("\nMultiplication (a * b):\n", a * b)
print("\nMultiplication using np.multiply:\n", np.multiply(a, b))

# --- Mathematical Functions ---
print("\nExponential of b:\n", np.exp(b))
print("\nSquare root of b:\n", np.sqrt(b))
print("\nSine of a:\n", np.sin(a))
print("\nCosine of b:\n", np.cos(b))
print("\nNatural log of a:\n", np.log(a))

# --- Dot Product ---
print("\nDot product of e and f:\n", e.dot(f))


Array a:
 [1 2 3]

Array b:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]

Array c:
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

Array d (arange):
 [10 15 20]

Linspace array:
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

Full array (7s):
 [[7 7]
 [7 7]]

Identity matrix f:
 [[1. 0.]
 [0. 1.]]

Random array:
 [[0.96572501 0.17935081]
 [0.45405461 0.12106144]]

Empty array:
 [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]

Subtraction (a - b):
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]

Subtraction using np.subtract:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]

Addition (b + a):
 [[2.5 4.  6. ]
 [5.  7.  9. ]]

Addition using np.add:
 [[2.5 4.  6. ]
 [5.  7.  9. ]]

Division (a / b):
 [[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]

Division using np.div