<a href="https://colab.research.google.com/github/zeeshan-ahmed-ai-tech/Artificial-Neural-Network/blob/main/torch_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ===============================
# PyTorch Tensor Creation and Operations
# ===============================

import torch
import numpy as np

# --- Defining Tensors ---
t1 = torch.tensor([1, 2, 3, 4, 5])
t2 = torch.tensor([[1.5, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=torch.float32)
print("Tensor t1:\n", t1)
print("\nTensor t2:\n", t2)

# --- Converting a NumPy array to a Tensor ---
np_array = np.array([[10, 20, 30], [40, 50, 60]])
t3 = torch.from_numpy(np_array)
print("\nTensor from NumPy array:\n", t3)

# --- Tensor of zeros, ones, identity, constant, empty ---
print("\nZeros tensor:\n", torch.zeros((2, 3)))
print("\nOnes tensor:\n", torch.ones((2, 3)))
print("\nIdentity matrix:\n", torch.eye(3))
print("\nFull tensor (all 7s):\n", torch.full((2, 2), 7))
print("\nEmpty tensor (uninitialized values):\n", torch.empty((2, 3)))

# --- Creating sequences ---
print("\nArange (like NumPy):\n", torch.arange(0, 10, 2))
print("\nLinspace:\n", torch.linspace(0, 1, 5))
print("\nLogspace:\n", torch.logspace(0, 2, 5))  # 10^0 to 10^2

# --- Concatenation and splitting ---
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6]])
print("\nConcatenated:\n", torch.cat((a, b), dim=0))
print("\nSplit into 2 parts:\n", torch.split(a, 1))

# --- Squeeze / Unsqueeze ---
x = torch.tensor([[1, 2, 3]])
print("\nOriginal shape:", x.shape)
print("Squeezed shape:", torch.squeeze(x).shape)
print("Unsqueezed shape:", torch.unsqueeze(x, 0).shape)

# --- Reshape & Transpose ---
y = torch.arange(1, 7)
print("\nOriginal y:", y)
print("Reshaped y (2x3):\n", torch.reshape(y, (2, 3)))
print("\nTranspose of t2:\n", torch.t(t2))
print("\nTranspose using transpose():\n", torch.transpose(t2, 0, 1))

# --- Set random seed ---
torch.manual_seed(42)

# --- Random tensors ---
print("\nRandom tensor [0,1):\n", torch.rand((2, 2)))
print("\nRandom integer tensor:\n", torch.randint(0, 10, (2, 3)))
print("\nNormal distribution tensor (mean=0, var=1):\n", torch.randn((2, 2)))

# --- Basic operations ---
x = torch.tensor([1.0, 2.0, -3.0, 4.5])
y = torch.tensor([2.0, 4.0, 6.0, 8.0])

print("\nAbsolute values:\n", torch.abs(x))
print("\nAddition:\n", torch.add(x, y))
print("\nDivision:\n", torch.div(x, y))
print("\nMultiplication:\n", torch.mul(x, y))
print("\nSubtraction:\n", torch.sub(x, y))
print("\nCeil:\n", torch.ceil(x))
print("\nFloor:\n", torch.floor(x))
print("\nRemainder:\n", torch.remainder(x, 2))
print("\nSquare root of |x|:\n", torch.sqrt(torch.abs(x)))
print("\nRounded:\n", torch.round(x))
print("\nPower (x^2):\n", torch.pow(x, 2))


Tensor t1:
 tensor([1, 2, 3, 4, 5])

Tensor t2:
 tensor([[1.5000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000]])

Tensor from NumPy array:
 tensor([[10, 20, 30],
        [40, 50, 60]])

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Full tensor (all 7s):
 tensor([[7, 7],
        [7, 7]])

Empty tensor (uninitialized values):
 tensor([[2.8381e-11, 0.0000e+00, 0.0000e+00],
        [1.5046e-36, 1.0079e-14, 0.0000e+00]])

Arange (like NumPy):
 tensor([0, 2, 4, 6, 8])

Linspace:
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

Logspace:
 tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])

Concatenated:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Split into 2 parts:
 (tensor([[1, 2]]), tensor([[3, 4]]))

Original shape: torch.Size([1, 3])
Squeezed shape: torch.Size([3])
Unsqueezed shape: torch.Size([1, 1, 3])

Or